# Generated by Django 5.1.4 on 2025-02-11 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_title', models.CharField(max_length=255)),
                ('related_manga_title', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('description', models.TextField()),
                ('stock_price', models.FloatField()),
                ('current_selling_price', models.FloatField()),
                ('physical_position', models.CharField(max_length=255)),
                ('number_of_owned_copies', models.IntegerField()),
                ('copies_sold', models.JSONField(default=list)),
                ('useful_links', models.JSONField(default=list)),
                ('vinted_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
