# Generated by Django 5.1.4 on 2025-02-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0002_usertovariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertovariant',
            name='images',
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_images/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GeneralHandler.usertovariant')),
            ],
        ),
    ]
