# Generated by Django 5.1.4 on 2025-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0003_remove_usertovariant_images_variantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertomanga',
            name='animeclick_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertomanga',
            name='volume_doubles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='current_selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='stock_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='vinted_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
