# Generated by Django 5.1.4 on 2025-02-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0004_alter_usertomanga_animeclick_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertomanga',
            name='all_read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usertomanga',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
