# Generated by Django 5.1.4 on 2025-02-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0005_usertomanga_all_read_usertomanga_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertomanga',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
