# Generated by Django 5.1.4 on 2025-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0007_usertowishlistitem_wishlistimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertovariant',
            name='to_sell',
            field=models.BooleanField(default=False),
        ),
    ]
