# Generated by Django 5.1.6 on 2025-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0009_usertomanga_all_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertomanga',
            name='whole_series_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
