# Generated by Django 5.1.4 on 2025-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0011_usertomanga_whole_series_price_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertomanga',
            name='editor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usertomanga',
            name='manga_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertomanga',
            name='owned_volumes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertomanga',
            name='physical_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertomanga',
            name='volume_doubles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='physical_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='related_manga_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertovariant',
            name='variant_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertowishlistitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
