# Generated by Django 5.1.6 on 2025-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0013_alter_usertomanga_user_alter_usertovariant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoextrainfos',
            name='MANGA_STATS_TO_BE_MODIFIED',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertoextrainfos',
            name='manga_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
