# Generated by Django 5.1.4 on 2025-03-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0014_usertoextrainfos_manga_stats_to_be_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoextrainfos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usertomanga',
            constraint=models.UniqueConstraint(fields=('user', 'manga_title'), name='unique_user_manga'),
        ),
        migrations.AddConstraint(
            model_name='usertovariant',
            constraint=models.UniqueConstraint(fields=('user', 'variant_title'), name='unique_user_variant'),
        ),
        migrations.AddConstraint(
            model_name='usertowishlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_wishlistitem'),
        ),
    ]
