# Generated by Django 5.1.4 on 2025-03-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0015_alter_usertoextrainfos_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistimage',
            name='image',
            field=models.ImageField(unique=True, upload_to='wishlist_images/'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(fields=('variant', 'image'), name='unique_image_variant'),
        ),
        migrations.AddConstraint(
            model_name='wishlistimage',
            constraint=models.UniqueConstraint(fields=('wishlist_item', 'image'), name='unique_image_wishlistitem'),
        ),
    ]
