# Generated by Django 5.1.4 on 2025-03-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralHandler', '0016_alter_wishlistimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertowishlistitem',
            name='importance_rating',
            field=models.IntegerField(default=0),
        ),
    ]
